apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-platform
resources:
  - resources/namespace.yaml
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.6.4
patches:
  - patches/argocd-application-controller-clusterrolebinding.yaml
  - patches/argocd-server-clusterrolebinding.yaml
